import { BookingItem } from './types';

export const SAMPLE_BOOKINGS: BookingItem[] = [
  {
    id: 'GYG6H73M6WMV',
    referenceNumber: 'GYG6H73M6WMV',
    tourTitle: 'From Munich: Salzburg, Hallstatt & Lakes Private Day Trip',
    fareOption: 'Disability Fare – 26 September 2026',
    date: 'September 26, 2026, 10:00 AM',
    timestamp: new Date('2026-09-26T10:00:00').getTime(),
    participants: '1 x Adult (Age 18 - 99)',
    customerName: 'Marcel Reiner',
    customerEmail: 'customer-5mnycnkorphuz6b4@reply.getyourguide.com',
    customerPhone: '+436933029696',
    customerLanguage: 'German',
    tourLanguage: 'German (Live tour guide)',
    pickup: 'München Hauptbahnhof, Bayerstraße, München, Deutschland',
    mapsUrl: 'https://maps.google.com/?q=München+Hauptbahnhof+Bayerstraße',
    bookingUrl: 'https://supplier.getyourguide.com',
    price: '€ 9.60',
    priceAmount: 9.60,
    isReviewBooking: true,
    isLastMinute: true,
    receivedAt: '2026-09-25T13:45:00.000Z',
    status: 'last-minute',
  },
  {
    id: 'GYG4T92K8LP1',
    referenceNumber: 'GYG4T92K8LP1',
    tourTitle: 'Neuschwanstein Castle & Linderhof Palace Day Tour from Munich',
    fareOption: 'Standard Admission + Express Coach',
    date: 'September 27, 2026, 08:30 AM',
    timestamp: new Date('2026-09-27T08:30:00').getTime(),
    participants: '2 x Adult (Age 18 - 99)',
    customerName: 'Sophie Van Der Berg',
    customerEmail: 'customer-8vxk2m91pqw7@reply.getyourguide.com',
    customerPhone: '+31620448192',
    customerLanguage: 'English',
    tourLanguage: 'English (Live tour guide)',
    pickup: 'Karlsplatz 21 (Stachus), 80335 München',
    mapsUrl: 'https://maps.google.com/?q=Karlsplatz+21+Munchen',
    bookingUrl: 'https://supplier.getyourguide.com',
    price: '€ 138.00',
    priceAmount: 138.00,
    isReviewBooking: false,
    isLastMinute: false,
    receivedAt: '2026-09-25T11:20:00.000Z',
    status: 'confirmed',
  },
  {
    id: 'GYG9B11P4WXZ',
    referenceNumber: 'GYG9B11P4WXZ',
    tourTitle: 'Munich Bavarian Beer & Traditional Food Evening Tour',
    fareOption: 'Evening Tasting Experience with Dinner',
    date: 'September 28, 2026, 06:00 PM',
    timestamp: new Date('2026-09-28T18:00:00').getTime(),
    participants: '4 x Adult',
    customerName: 'Elena Rostova',
    customerEmail: 'customer-19zkv4mlo02x@reply.getyourguide.com',
    customerPhone: '+491764920199',
    customerLanguage: 'English',
    tourLanguage: 'English',
    pickup: 'Marienplatz Fish Fountain (Fischbrunnen), München',
    mapsUrl: 'https://maps.google.com/?q=Marienplatz+Munchen',
    bookingUrl: 'https://supplier.getyourguide.com',
    price: '€ 236.00',
    priceAmount: 236.00,
    isReviewBooking: false,
    isLastMinute: false,
    receivedAt: '2026-09-24T18:10:00.000Z',
    status: 'confirmed',
  },
  {
    id: 'GYG6H73QFYYK',
    referenceNumber: 'GYG6H73QFYYK',
    tourTitle: 'From Salzburg: Hallstatt Salt Mine & Skywalk Private Tour',
    fareOption: 'Private Tour with Hotel Pickup',
    date: 'October 25, 2026, 09:00 AM',
    timestamp: new Date('2026-10-25T09:00:00').getTime(),
    participants: '2 x Adults (Age 0 - 99)',
    customerName: 'Kazuomi Kaneto',
    customerEmail: 'customer-gyg6h73@reply.getyourguide.com',
    customerPhone: '+6587985475',
    customerLanguage: 'Japanese',
    tourLanguage: 'English (Live tour guide)',
    pickup: 'Sheraton Grand Salzburg, Auerspergstraße 4, 5020 Salzburg',
    mapsUrl: 'https://maps.google.com/?q=Sheraton+Grand+Salzburg',
    bookingUrl: 'https://supplier.getyourguide.com',
    price: '€ 620.00',
    priceAmount: 620.00,
    isReviewBooking: false,
    isLastMinute: false,
    receivedAt: '2026-09-24T08:32:04.000Z',
    status: 'cancelled',
  },
];
