/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnspruchPruefenIndexRouteImport } from './routes/anspruch-pruefen.index'
import { Route as AnspruchPruefenTypRouteImport } from './routes/anspruch-pruefen.$typ'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnspruchPruefenIndexRoute = AnspruchPruefenIndexRouteImport.update({
  id: '/anspruch-pruefen/',
  path: '/anspruch-pruefen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnspruchPruefenTypRoute = AnspruchPruefenTypRouteImport.update({
  id: '/anspruch-pruefen/$typ',
  path: '/anspruch-pruefen/$typ',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anspruch-pruefen/$typ': typeof AnspruchPruefenTypRoute
  '/anspruch-pruefen/': typeof AnspruchPruefenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anspruch-pruefen/$typ': typeof AnspruchPruefenTypRoute
  '/anspruch-pruefen': typeof AnspruchPruefenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anspruch-pruefen/$typ': typeof AnspruchPruefenTypRoute
  '/anspruch-pruefen/': typeof AnspruchPruefenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anspruch-pruefen/$typ' | '/anspruch-pruefen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anspruch-pruefen/$typ' | '/anspruch-pruefen'
  id: '__root__' | '/' | '/anspruch-pruefen/$typ' | '/anspruch-pruefen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnspruchPruefenTypRoute: typeof AnspruchPruefenTypRoute
  AnspruchPruefenIndexRoute: typeof AnspruchPruefenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anspruch-pruefen/': {
      id: '/anspruch-pruefen/'
      path: '/anspruch-pruefen'
      fullPath: '/anspruch-pruefen/'
      preLoaderRoute: typeof AnspruchPruefenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anspruch-pruefen/$typ': {
      id: '/anspruch-pruefen/$typ'
      path: '/anspruch-pruefen/$typ'
      fullPath: '/anspruch-pruefen/$typ'
      preLoaderRoute: typeof AnspruchPruefenTypRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnspruchPruefenTypRoute: AnspruchPruefenTypRoute,
  AnspruchPruefenIndexRoute: AnspruchPruefenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
