#!/usr/bin/env python3
"""
Converts brand logo images to ZPL ^GF (Graphic Field) hex strings
and writes a Dart file embedding them so they can be used in ZPL labels.

Label graphic area: 80×80 dots (fits in ~10mm on 203dpi ZD220)
The logo is placed in the top-right corner of the 50x30mm label.
"""

import os
from PIL import Image, ImageOps, ImageFilter

ASSETS_DIR = os.path.join(os.path.dirname(__file__), '..', 'assets', 'restaurantlogos')
OUTPUT_DART = os.path.join(os.path.dirname(__file__), '..', 'lib', 'utils', 'brand_logos_zpl.dart')

# Target size in dots on the label (top-right corner, 80×80 dots)
LOGO_WIDTH_DOTS  = 80
LOGO_HEIGHT_DOTS = 80

# Brand name → asset filename (without extension search)
BRANDS = {
    'devilssmashburger':  ('devilssmashburger.png',  'Devils Smash Burger'),
    'crispychickenlab':   ('crispychickenlab.jpeg',  'Crispy Chicken Lab'),
    'tacotastic':         ('tacotastic.jpeg',         'Tacotastic'),
    'thebowlspot':        ('thebowlspot.jpeg',         'The Bowl Spot'),
}

def image_to_zpl_gf(path: str, width_dots: int, height_dots: int) -> tuple[str, int, int]:
    """
    Convert an image to ZPL ^GF A (ASCII hex) format.
    Returns (hex_string, bytes_per_row, total_bytes).
    """
    img = Image.open(path).convert('RGBA')

    # White-fill transparent areas (thermal = white paper)
    background = Image.new('RGBA', img.size, (255, 255, 255, 255))
    background.paste(img, mask=img.split()[3])
    img = background.convert('RGB')

    # Resize to target dots (maintain aspect, pad with white)
    img.thumbnail((width_dots, height_dots), Image.LANCZOS)
    canvas = Image.new('RGB', (width_dots, height_dots), (255, 255, 255))
    offset = ((width_dots - img.width) // 2, (height_dots - img.height) // 2)
    canvas.paste(img, offset)

    # Sharpen a bit to improve legibility at small size
    canvas = canvas.filter(ImageFilter.SHARPEN)

    # Convert to 1-bit (black = 1 on thermal label)
    # Invert so dark pixels become 1 (printed)
    bw = canvas.convert('L')  # grayscale
    # Apply threshold: pixels darker than 128 → black (1), lighter → white (0)
    bw = bw.point(lambda x: 0 if x > 128 else 255)  # white=0 for ZPL (no ink)
    bw = bw.convert('1')  # true 1-bit

    # ZPL GF: bits packed MSB first, each row padded to byte boundary
    bytes_per_row = (width_dots + 7) // 8
    total_bytes   = bytes_per_row * height_dots

    hex_lines = []
    pixels = list(bw.getdata())
    for row in range(height_dots):
        row_bits = pixels[row * width_dots:(row + 1) * width_dots]
        byte_chunks = []
        for col in range(bytes_per_row):
            byte_val = 0
            for bit in range(8):
                px_idx = col * 8 + bit
                if px_idx < width_dots:
                    # In PIL 1-bit: 0=black, 255=white; we want 1=ink(black)
                    if row_bits[px_idx] == 0:  # black pixel → ink
                        byte_val |= (1 << (7 - bit))
            byte_chunks.append(f'{byte_val:02X}')
        hex_lines.append(''.join(byte_chunks))

    return ''.join(hex_lines), bytes_per_row, total_bytes


def main():
    results = {}

    for key, (filename, display_name) in BRANDS.items():
        path = os.path.join(ASSETS_DIR, filename)
        if not os.path.exists(path):
            print(f'  [SKIP] {path} not found')
            continue

        print(f'  Converting {display_name}...')
        hex_data, bpr, total = image_to_zpl_gf(path, LOGO_WIDTH_DOTS, LOGO_HEIGHT_DOTS)
        results[key] = {
            'display': display_name,
            'hex': hex_data,
            'bpr': bpr,
            'total': total,
        }
        print(f'    → {total} bytes, {bpr} bytes/row, hex len={len(hex_data)}')

    # Write Dart file
    dart_lines = [
        '// AUTO-GENERATED by scripts/convert_logos_to_zpl.py — DO NOT EDIT MANUALLY',
        '//',
        '// Contains pre-converted brand logos as ZPL ^GF hex strings.',
        '// Each logo is 80×80 dots (≈10mm on 203dpi ZD220).',
        '',
        '/// Returns the ZPL ^GF field string for [brandKey], or empty string if unknown.',
        '/// brandKey is the lowercase brand identifier (e.g. "devilssmashburger").',
        'String brandLogoGf(String brandKey) {',
        '  switch (brandKey.toLowerCase().replaceAll(RegExp(r\'[^a-z]\'), \'\')) {',
    ]

    for key, data in results.items():
        bpr   = data['bpr']
        total = data['total']
        hex_  = data['hex']
        # ^GF A,<total>,<total>,<bpr>,<hex>
        gf = f'^GFA,{total},{total},{bpr},{hex_}'
        dart_lines += [
            f"    case '{key}':",
            f"      return",
            f"        '{gf}';",
        ]

    dart_lines += [
        "    default:",
        "      return '';",
        "  }",
        "}",
        "",
        "/// All known brand keys.",
        "const List<String> kBrandLogoKeys = [",
    ]
    for key in results:
        dart_lines.append(f"  '{key}',")
    dart_lines += ["];", ""]

    with open(OUTPUT_DART, 'w') as f:
        f.write('\n'.join(dart_lines))

    print(f'\nWrote {OUTPUT_DART}')


if __name__ == '__main__':
    main()
