import 'package:hive/hive.dart';

part 'brand.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 2) // Assuming MaterialItem is 0, InventoryLogItem is 1
class Brand extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime createdAt;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String? description;

  @HiveField(4)
  final String? imageUrl;

  Brand({
    required this.id,
    required this.createdAt,
    required this.name,
    this.description,
    this.imageUrl,
  });

  factory Brand.fromJson(Map<String, dynamic> json) {
    String? id = json['id'] as String?;
    String? name = json['name'] as String?;
    String? createdAtString = json['created_at'] as String?;

    if (id == null) {
      print("Brand.fromJson WARNING: 'id' is null in JSON data. Using placeholder. JSON: $json");
      id = 'UNKNOWN_BRAND_ID_${DateTime.now().millisecondsSinceEpoch}'; // Or handle as an error
    }
    if (name == null) {
      print("Brand.fromJson WARNING: 'name' is null in JSON data. Using placeholder. JSON: $json");
      name = 'Unknown Brand'; // Or handle as an error
    }
    if (createdAtString == null) {
      print("Brand.fromJson WARNING: 'created_at' is null in JSON data. Using current time. JSON: $json");
      // Fallback to current time, or throw an error if this is unacceptable
      createdAtString = DateTime.now().toIso8601String();
    }
    
    DateTime createdAt;
    try {
      createdAt = DateTime.parse(createdAtString);
    } catch (e) {
      print("Brand.fromJson ERROR: Could not parse 'created_at' string '$createdAtString'. Using current time. Error: $e. JSON: $json");
      createdAt = DateTime.now();
    }

    return Brand(
      id: id,
      createdAt: createdAt,
      name: name,
      description: json['description'] as String?,
      imageUrl: json['image_url'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'description': description,
      'image_url': imageUrl,
    };
  }
}
