import 'package:hive/hive.dart';

part 'material_item.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for Hive
class MaterialItem extends HiveObject { // Extend HiveObject
  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime createdAt;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String unitOfMeasure; // e.g., 'kilo', 'piece', 'ml'
  
  @HiveField(4)
  double currentQuantity;

  @HiveField(5)
  final String? sellerName;

  @HiveField(6)
  final String? itemNumber;

  @HiveField(7)
  final String? category; // Added category field
  
  @HiveField(8)
  final String? itemImageUrl; // Added for item-specific image
  
  @HiveField(9)
  final String? geminiInfo; // Added for Gemini-specific information

  @HiveField(10)
  double? weightedAverageCost; // Added for weighted average cost

  @HiveField(11) // Ensure this HiveField index is unique and sequential
  final double? notifyWhenQuantity;

  @HiveField(12)
  final String? arabicName; // Added for Arabic translation

  MaterialItem({
    required this.id,
    required this.createdAt,
    required this.name,
    required this.unitOfMeasure,
    required this.currentQuantity,
    this.sellerName,
    this.itemNumber,
    this.category, // Added to constructor
    this.itemImageUrl, // Added to constructor
    this.geminiInfo, // Added to constructor
    this.weightedAverageCost, // Added to constructor
    this.notifyWhenQuantity, // Added to constructor
    this.arabicName, // Added to constructor
  });

  factory MaterialItem.fromJson(Map<String, dynamic> json) {
    return MaterialItem(
      id: json['id'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
      name: json['name'] as String,
      unitOfMeasure: json['unit_of_measure'] as String,
      currentQuantity: (json['current_quantity'] as num).toDouble(),
      sellerName: json['seller_name'] as String?,
      itemNumber: json['item_number'] as String?,
      category: json['category'] as String?, // Added category from JSON
      itemImageUrl: json['item_image_url'] as String?, // Consistent with DB and toJson
      geminiInfo: json['gemini_info'] as String?, // Added geminiInfo from JSON
      weightedAverageCost: (json['average_unit_cost'] as num?)?.toDouble(), // Changed to average_unit_cost
      notifyWhenQuantity: (json['notify_when_quantity'] as num?)?.toDouble(), // Added notifyWhenQuantity from JSON
      arabicName: json['arabic_name'] as String?, // Added arabicName from JSON
    );
  }

  Map<String, dynamic> toJson() { // For creating new items
    return {
      'name': name,
      'unit_of_measure': unitOfMeasure,
      'current_quantity': currentQuantity,
      'seller_name': sellerName,
      'item_number': itemNumber,
      'category': category, // Added category to JSON
      'item_image_url': itemImageUrl, // Added itemImageUrl to JSON
      'gemini_info': geminiInfo, // Added geminiInfo to JSON
      'notify_when_quantity': notifyWhenQuantity, // Added notifyWhenQuantity to JSON
      'arabic_name': arabicName, // Added arabicName to JSON
    };
  }

  // For updating, you might want a separate method or include id
   Map<String, dynamic> toJsonForUpdate() { // For updating existing items
    return {
      'id': id,
      'name': name,
      'unit_of_measure': unitOfMeasure,
      'current_quantity': currentQuantity,
      'seller_name': sellerName,
      'item_number': itemNumber,
      'category': category, // Added category to JSON for updates
      'item_image_url': itemImageUrl, // Added itemImageUrl to JSON for updates
      'gemini_info': geminiInfo, // Added geminiInfo to JSON for updates
      'average_unit_cost': weightedAverageCost, // Changed to average_unit_cost
      'notify_when_quantity': notifyWhenQuantity, // Added notifyWhenQuantity to JSON for updates
      'arabic_name': arabicName, // Added arabicName to JSON for updates
    };
  }
}
