// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0j_o5Qrcnr_kA3xr6N5AE8LawgcmfGlc',
    appId: '1:671236247932:android:e5bce89d9574345b67d4f9',
    messagingSenderId: '671236247932',
    projectId: 'restaurantadmin-e2555',
    storageBucket: 'restaurantadmin-e2555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4ZvS5S8G3JEwX-hKiAfcgbX11Myx1ms',
    appId: '1:671236247932:ios:2f31d2e87feb612167d4f9',
    messagingSenderId: '671236247932',
    projectId: 'restaurantadmin-e2555',
    storageBucket: 'restaurantadmin-e2555.firebasestorage.app',
    iosBundleId: 'com.mycoolrestaurant.adminapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CSed_i5Op2n6J6syNdcE58PDijbXdW8',
    appId: '1:671236247932:web:98477f0473e5259767d4f9',
    messagingSenderId: '671236247932',
    projectId: 'restaurantadmin-e2555',
    authDomain: 'restaurantadmin-e2555.firebaseapp.com',
    storageBucket: 'restaurantadmin-e2555.firebasestorage.app',
    measurementId: 'G-J6H6VZMDF9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4ZvS5S8G3JEwX-hKiAfcgbX11Myx1ms',
    appId: '1:671236247932:ios:0262ae21d2a76fad67d4f9',
    messagingSenderId: '671236247932',
    projectId: 'restaurantadmin-e2555',
    storageBucket: 'restaurantadmin-e2555.firebasestorage.app',
    iosBundleId: 'com.example.restaurantadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3CSed_i5Op2n6J6syNdcE58PDijbXdW8',
    appId: '1:671236247932:web:6b31bb03553e862367d4f9',
    messagingSenderId: '671236247932',
    projectId: 'restaurantadmin-e2555',
    authDomain: 'restaurantadmin-e2555.firebaseapp.com',
    storageBucket: 'restaurantadmin-e2555.firebasestorage.app',
    measurementId: 'G-DT5VL37STD',
  );

}