import 'dart:async'; // Import for StreamSubscription
import 'package:firebase_core/firebase_core.dart'; // Added for Firebase
import 'firebase_options.dart'; // This will be generated by FlutterFire CLI. Uncomment after generation.
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb; // Import kIsWeb
import 'package:flutter/services.dart'; // For Clipboard
import 'package:flutter_dotenv/flutter_dotenv.dart'; // Re-enabled dotenv
import 'package:provider/provider.dart'; // Added provider import
import 'package:restaurantadmin/providers/cart_provider.dart'; // Added CartProvider import
import 'package:restaurantadmin/providers/user_profile_provider.dart'; // Will create this
import 'package:restaurantadmin/services/user_service.dart'; // Import UserService
import 'package:restaurantadmin/models/profile.dart'
    as app_profile; // Import Profile model
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:restaurantadmin/screens/main_screen.dart';
import 'package:restaurantadmin/screens/auth/login_screen.dart';
import 'package:restaurantadmin/screens/driver/driver_app_shell.dart';
import 'package:restaurantadmin/screens/scanned_order_receipt_screen.dart'; // Import the new screen
import 'package:restaurantadmin/screens/worker/worker_app_shell.dart';
import 'package:hive_flutter/hive_flutter.dart'; // Import Hive

// Import your adapters here once created, e.g.:
import 'package:restaurantadmin/models/material_item.dart'; // Import MaterialItem model
import 'package:restaurantadmin/models/inventory_log_item.dart'; // Import InventoryLogItem model
import 'package:restaurantadmin/models/brand.dart'; // Import Brand model
import 'package:restaurantadmin/models/menu_category.dart'; // Import MenuCategory model
import 'package:restaurantadmin/models/menu_item_model.dart'; // Import MenuItem model
import 'package:restaurantadmin/models/worker_cache_models.dart'; // Import worker cache models
import 'package:restaurantadmin/services/local_scan_server.dart'; // Import the local server
import 'package:restaurantadmin/widgets/global_purchase_listener.dart';
import 'package:restaurantadmin/screens/receipt_scanner_screen.dart';
import 'package:restaurantadmin/widgets/global_order_listener.dart';
import 'package:restaurantadmin/services/push_notification_service.dart'; // Import push notification service
import 'package:firebase_messaging/firebase_messaging.dart'; // For background handler

final GlobalKey<NavigatorState> appNavigatorKey = GlobalKey<NavigatorState>();

// Top-level const declarations for --dart-define values
const String supabaseUrlFromEnv = String.fromEnvironment(
  'SUPABASE_URL',
  defaultValue: '',
);
const String supabaseAnonKeyFromEnv = String.fromEnvironment(
  'SUPABASE_ANON_KEY',
  defaultValue: '',
);
// const String geminiApiKeyFromEnv = String.fromEnvironment('GEMINI_API_KEY', defaultValue: ''); // If you also pass Gemini key via --dart-define
// Listener feature flags (from --dart-define). Empty means we will check .env or use defaults
const String enableOrderListenerFromEnv = String.fromEnvironment(
  'ENABLE_GLOBAL_ORDER_LISTENER',
  defaultValue: '',
);
const String enablePurchaseListenerFromEnv = String.fromEnvironment(
  'ENABLE_GLOBAL_PURCHASE_LISTENER',
  defaultValue: '',
);

bool _parseBoolFlag(String? v, {bool defaultValue = false}) {
  if (v == null || v.isEmpty) return defaultValue;
  final s = v.toLowerCase().trim();
  return s == 'true' || s == '1' || s == 'yes' || s == 'y';
}


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Start the local scan server on non-web platforms
  if (!kIsWeb) {
    // Global listener: push ReceiptScannerScreen when an image arrives
    LocalScanServer().onImageReceived = (bytes) {
      final nav = appNavigatorKey.currentState;
      if (nav == null) return;
      // If we’re already on the scanner, just let that screen handle it.
      final currentRoute = ModalRoute.of(nav.context)?.settings.name ?? '';
      if (currentRoute == '/receipt-scanner') {
        return;
      }
      nav.push(
        MaterialPageRoute(
          settings: const RouteSettings(name: '/receipt-scanner'),
          builder: (_) => ReceiptScannerScreen(initialImageBytes: bytes),
        ),
      );
    };

    await LocalScanServer().startServer();
  }

  try {
    // Use local variables that can be updated by .env if needed on mobile
    String supabaseUrl = supabaseUrlFromEnv;
    String supabaseAnonKey = supabaseAnonKeyFromEnv;
    // String geminiApiKey = geminiApiKeyFromEnv; // For Gemini API Key

    // Listener flags (defaults: order off, purchase on). Can be overridden by --dart-define or .env
    bool enableOrderListener = _parseBoolFlag(enableOrderListenerFromEnv, defaultValue: false);
    bool enablePurchaseListener = _parseBoolFlag(enablePurchaseListenerFromEnv, defaultValue: true);

    // Initialize Firebase
    // Ensure firebase_options.dart is generated by running `flutterfire configure`
    // and uncomment the import at the top of this file.
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions
            .currentPlatform, // Uncomment after firebase_options.dart is generated
      );
      print('INFO: Firebase initialized successfully.');
      
      // Register background message handler
      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
    } catch (e) {
      print('WARNING: Firebase initialization failed. Error: $e');
      // Depending on how critical Firebase is at startup, you might want to handle this error.
      // For App Distribution, the app needs to build, but full Firebase functionality might not be needed for the app to start.
    }

    // If compile-time variables are not present, load from .env file for any platform.
    bool dartDefineWasEmpty =
        supabaseUrlFromEnv.isEmpty || supabaseAnonKeyFromEnv.isEmpty;
    if (dartDefineWasEmpty) {
      print(
        'INFO: --dart-define values for Supabase not found. Attempting to load from .env file...',
      );
      try {
        await dotenv.load(fileName: ".env");
        supabaseUrl = dotenv.env['SUPABASE_URL'] ?? '';
        supabaseAnonKey = dotenv.env['SUPABASE_ANON_KEY'] ?? '';
        // If not provided via --dart-define, allow .env to control listeners
        if (enableOrderListenerFromEnv.isEmpty) {
          enableOrderListener = _parseBoolFlag(dotenv.env['ENABLE_GLOBAL_ORDER_LISTENER'], defaultValue: enableOrderListener);
        }
        if (enablePurchaseListenerFromEnv.isEmpty) {
          enablePurchaseListener = _parseBoolFlag(dotenv.env['ENABLE_GLOBAL_PURCHASE_LISTENER'], defaultValue: enablePurchaseListener);
        }

        if (supabaseUrl.isNotEmpty && supabaseAnonKey.isNotEmpty) {
          print('INFO: Loaded Supabase keys from .env file.');
        } else {
          print('WARNING: .env file did not provide Supabase keys.');
        }
      } catch (e) {
        print('WARNING: Could not load .env file. Error: $e');
      }
    }

    // Final check if keys are available
    if (supabaseUrl.isEmpty || supabaseAnonKey.isEmpty) {
      print(
        'CRITICAL: SUPABASE_URL or SUPABASE_ANON_KEY is not set. App may not function correctly.',
      );
      // For a production app, you might want to throw an error here or display a specific error UI.
      // runApp(ErrorApp(message: 'Supabase configuration is missing.'));
      // return; // Prevent further execution if critical config is missing
    } else {
      print('Using Supabase URL: $supabaseUrl');
      print(
        'Supabase Anon Key is ${supabaseAnonKey.isNotEmpty ? "Loaded" : "MISSING"}',
      );
    }

    // Validate Supabase configuration early to avoid runtime URI errors
    final parsedUri = Uri.tryParse(supabaseUrl);
    final hasValidUrl =
        parsedUri != null && parsedUri.hasScheme && parsedUri.host.isNotEmpty;
    if (!hasValidUrl || supabaseAnonKey.isEmpty) {
      print(
        'CRITICAL: Invalid Supabase configuration. URL or Anon Key missing/malformed.',
      );
      runApp(
        MaterialApp(
          home: Scaffold(
            body: Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Text(
                  'Missing/invalid Supabase configuration.\n\n'
                  'Please set SUPABASE_URL and SUPABASE_ANON_KEY via --dart-define or a .env file at project root.\n\n'
                  'Example .env:\n'
                  'SUPABASE_URL=https://YOUR_PROJECT_REF.supabase.co\n'
                  'SUPABASE_ANON_KEY=YOUR_ANON_KEY',
                  textAlign: TextAlign.center,
                ),
              ),
            ),
          ),
        ),
      );
      return;
    }

    // Initialize Hive
    await Hive.initFlutter();
    // Register Adapters
    Hive.registerAdapter(MaterialItemAdapter()); // Register MaterialItemAdapter
    Hive.registerAdapter(
      InventoryLogItemAdapter(),
    ); // Register InventoryLogItemAdapter
    Hive.registerAdapter(BrandAdapter()); // Register BrandAdapter
    Hive.registerAdapter(MenuCategoryAdapter()); // Register MenuCategoryAdapter
    Hive.registerAdapter(MenuItemAdapter()); // Register MenuItemAdapter
    
    // Register worker cache model adapters
    Hive.registerAdapter(CachedBrandAdapter());
    Hive.registerAdapter(CachedCategoryAdapter());
    Hive.registerAdapter(CachedMenuItemAdapter());
    Hive.registerAdapter(CachedMaterialAdapter());
    Hive.registerAdapter(CachedMenuItemMaterialAdapter());
    Hive.registerAdapter(WorkerCacheMetadataAdapter());

    // Open any globally used boxes
    await Hive.openBox(
      'app_settings',
    ); // For storing cache timestamps or general settings
    await Hive.openBox<List<dynamic>>('menuCategoriesBox');
    await Hive.openBox<Map<String, List<dynamic>>>('menuItemsBox');

    await Supabase.initialize(
      url: supabaseUrl, // Use value from String.fromEnvironment
      anonKey: supabaseAnonKey, // Use value from String.fromEnvironment
    );
    
    // Note: Push notifications will be initialized after login for admin users only
    
    runApp(
      MultiProvider(
        providers: [
          ChangeNotifierProvider(create: (context) => CartProvider()),
          ChangeNotifierProvider(create: (context) => UserProfileProvider()),
        ],
        child: RestaurantManagerApp(
          enableOrderListener: enableOrderListener,
          enablePurchaseListener: enablePurchaseListener,
        ),
      ),
    );
  } catch (e) {
    print('CRITICAL: Error during app initialization: $e');
    // In a real app, show a user-friendly error screen
    runApp(
      MaterialApp(
        home: Scaffold(body: Center(child: Text('Initialization Error: $e'))),
      ),
    );
  }
}

class RestaurantManagerApp extends StatelessWidget {
  final bool enableOrderListener;
  final bool enablePurchaseListener;
  const RestaurantManagerApp({super.key, required this.enableOrderListener, required this.enablePurchaseListener});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: appNavigatorKey,
      title: 'Restaurant Manager',
      theme: ThemeData(
        primaryColor: Colors.blue,
        scaffoldBackgroundColor: Colors.white,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0.5,
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 17,
            fontWeight: FontWeight.w600,
          ),
          iconTheme: IconThemeData(color: Colors.blue),
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.white,
          selectedItemColor: Colors.blue,
          unselectedItemColor: Colors.grey,
          elevation: 0.5,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      debugShowCheckedModeBanner: false,
      initialRoute: AuthGate.routeName, // Set initial route to AuthGate
      routes: {
        AuthGate.routeName: (context) => const AuthGate(),
        LoginScreen.routeName: (context) => const LoginScreen(),
        MainScreen.routeName: (context) => const MainScreen(),
        DriverAppShell.routeName: (context) => const DriverAppShell(),
        WorkerAppShell.routeName: (context) => const WorkerAppShell(),
        ScannedOrderReceiptScreen.routeName: (context) =>
            const ScannedOrderReceiptScreen(),
      },
      builder: (context, child) {
        Widget built = child ?? const SizedBox();
        if (enablePurchaseListener) {
          built = GlobalPurchaseListener(child: built);
        }
        if (enableOrderListener) {
          built = GlobalOrderListener(child: built);
        }
        return built;
      },
    );
  }
}

// Simple Auth Gate
class AuthGate extends StatefulWidget {
  static const routeName = '/auth-gate'; // Define routeName for AuthGate
  const AuthGate({super.key});

  @override
  State<AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<AuthGate> {
  final UserService _userService = UserService();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<AuthState>(
      stream: Supabase.instance.client.auth.onAuthStateChange,
      builder: (context, snapshot) {
        // Important: Supabase client initializes session from localStorage asynchronously.
        // The stream will initially emit the current state (potentially null if session not loaded yet)
        // and then emit again once the session is loaded from storage or if it changes.

        if (snapshot.connectionState == ConnectionState.waiting) {
          // This might be shown briefly while the stream is connecting.
          // Or if Supabase is still trying to load the initial session.
          print("AuthGate: Stream connection waiting.");
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(
                key: ValueKey("AuthGateStreamWaiting"),
              ),
            ),
          );
        }

        if (snapshot.hasError) {
          print("AuthGate: Stream error: ${snapshot.error}");
          // Handle error, perhaps navigate to login or show error message
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (mounted &&
                ModalRoute.of(context)?.settings.name !=
                    LoginScreen.routeName) {
              Navigator.pushReplacementNamed(context, LoginScreen.routeName);
            }
          });
          return const Scaffold(
            body: Center(child: Text("Auth Error. Redirecting...")),
          );
        }

        final authState = snapshot.data;
        final user = authState?.session?.user;

        if (user != null) {
          // User is logged in (or session restored)
          // Now fetch profile and navigate
          print(
            "AuthGate: User session available (User ID: ${user.id}). Fetching profile.",
          );
          return FutureBuilder<app_profile.Profile?>(
            future: _userService.getUserProfile(user.id),
            builder: (context, profileSnapshot) {
              if (profileSnapshot.connectionState == ConnectionState.waiting) {
                print("AuthGate: Fetching profile...");
                return const Scaffold(
                  body: Center(
                    child: CircularProgressIndicator(
                      key: ValueKey("AuthGateProfileLoading"),
                    ),
                  ),
                );
              }

              if (profileSnapshot.hasError ||
                  !profileSnapshot.hasData ||
                  profileSnapshot.data == null) {
                print(
                  "AuthGate: Error fetching profile or profile is null. Error: ${profileSnapshot.error}",
                );
                // Profile fetch failed or no profile, sign out and redirect to login
                WidgetsBinding.instance.addPostFrameCallback((_) async {
                  if (mounted) {
                    await Supabase.instance.client.auth
                        .signOut(); // Ensure clean logout
                    if (ModalRoute.of(context)?.settings.name !=
                        LoginScreen.routeName) {
                      Navigator.pushReplacementNamed(
                        context,
                        LoginScreen.routeName,
                      );
                    }
                  }
                });
                return const Scaffold(
                  body: Center(child: Text("Profile error. Redirecting...")),
                );
              }

              final profile = profileSnapshot.data!;
              // Update UserProfileProvider after build only if profile changed
              WidgetsBinding.instance.addPostFrameCallback((_) {
                if (mounted) {
                  final userProfileProvider = Provider.of<UserProfileProvider>(context, listen: false);
                  if (userProfileProvider.profile?.id != profile.id) {
                    userProfileProvider.setProfile(profile);
                  }
                }
              });

              // Perform navigation after build
              WidgetsBinding.instance.addPostFrameCallback((_) {
                if (!mounted) return;

                // Normalize role defensively and add hard override for known worker account
                final rawRole = (profile.role).toString();
                final role = rawRole.trim().toLowerCase();
                final email = (profile.email ?? '').trim().toLowerCase();
                final isKnownWorker = email == 'worker@example.com';

                String effectiveRole = role;
                if (isKnownWorker && (role.isEmpty || !(role == 'admin' || role == 'driver' || role == 'worker'))) {
                  effectiveRole = 'worker';
                }

                switch (effectiveRole) {
                  case 'admin':
                    print('[AuthGate] Admin user detected. Email: $email');
                    
                    // Initialize push notifications for admin only (youssef@gmail.com)
                    if (email == 'youssef@gmail.com') {
                      print('[AuthGate] Initializing push notifications for admin...');
                      Future.microtask(() async {
                        try {
                          print('[AuthGate] Calling PushNotificationService.initialize()...');
                          await PushNotificationService().initialize();
                          print('INFO: Push notification service initialized for admin.');
                        } catch (e) {
                          print('WARNING: Push notification service initialization failed: $e');
                          print('ERROR STACK: ${StackTrace.current}');
                        }
                      });
                    } else {
                      print('[AuthGate] Not youssef@gmail.com, skipping push notifications. Email was: $email');
                    }
                    
                    if (ModalRoute.of(context)?.settings.name != MainScreen.routeName) {
                      Navigator.pushReplacementNamed(context, MainScreen.routeName);
                    }
                    break;
                  case 'driver':
                    if (ModalRoute.of(context)?.settings.name != DriverAppShell.routeName) {
                      Navigator.pushReplacementNamed(context, DriverAppShell.routeName);
                    }
                    break;
                  case 'worker':
                    if (ModalRoute.of(context)?.settings.name != WorkerAppShell.routeName) {
                      Navigator.pushReplacementNamed(context, WorkerAppShell.routeName);
                    }
                    break;
                  default:
                    // Unknown role: attempt to self-heal for known worker via Edge Function, else sign out
                    if (isKnownWorker) {
                      () async {
                        try {
                          final user = Supabase.instance.client.auth.currentUser;
                          if (user != null) {
                            await Supabase.instance.client.functions.invoke(
                              'ensure-worker-profile',
                              body: {
                                'userId': user.id,
                                'email': user.email,
                                'fullName': 'Kitchen Worker',
                              },
                            );
                          }
                        } catch (_) {}
                        if (!mounted) return;
                        if (ModalRoute.of(context)?.settings.name != WorkerAppShell.routeName) {
                          Navigator.pushReplacementNamed(context, WorkerAppShell.routeName);
                        }
                      }();
                    } else {
                      Supabase.instance.client.auth.signOut();
                      if (ModalRoute.of(context)?.settings.name != LoginScreen.routeName) {
                        Navigator.pushReplacementNamed(context, LoginScreen.routeName);
                      }
                    }
                    break;
                }
              });
              // Return a loading indicator while navigation is scheduled
              return const Scaffold(
                body: Center(

                  child: CircularProgressIndicator(
                    key: ValueKey("AuthGateNavigating"),
                  ),
                ),
              );
            },
          );
        } else {
          // No user session: go to the unified Login screen
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (mounted &&
                ModalRoute.of(context)?.settings.name !=
                    LoginScreen.routeName) {
              Navigator.pushReplacementNamed(context, LoginScreen.routeName);
            }
          });
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
      },
    );

}
}


// Very Basic Login Screen (for development/testing) - This can likely be removed if LoginScreen is robust
class BasicLoginScreen extends StatefulWidget {
  static const routeName = '/basic-login'; // Added routeName
  const BasicLoginScreen({super.key});

  @override
  State<BasicLoginScreen> createState() => _BasicLoginScreenState();
}

class _BasicLoginScreenState extends State<BasicLoginScreen> {
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  bool _isLoading = false;

  Future<void> _signIn() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    try {
      final AuthResponse res = await Supabase.instance.client.auth
          .signInWithPassword(
            email: _emailController.text.trim(),
            password: _passwordController.text.trim(),
          );
      // AuthGate's onAuthStateChange listener will handle redirection and profile fetching.
      if (res.user != null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Signed in successfully! Redirecting...'),
              backgroundColor: Colors.green,
            ),
          );
        }
      } else {
        if (mounted) {
          _showCopyableError(context, 'Sign in failed. Check credentials.');
        }
      }
    } on AuthException catch (e) {
      if (mounted) {
        _showCopyableError(context, 'Sign in error: ${e.message}');
      }
    } catch (e) {
      if (mounted) {
        _showCopyableError(context, 'An unexpected error occurred: $e');
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showCopyableError(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            const Icon(Icons.error_outline, color: Colors.white, size: 20),
            const SizedBox(width: 8),
            Expanded(child: Text(message, maxLines: 3, overflow: TextOverflow.ellipsis)),
          ],
        ),
        backgroundColor: Colors.red[700],
        duration: const Duration(seconds: 8),
        behavior: SnackBarBehavior.floating,
        action: SnackBarAction(
          label: '📋 COPY',
          textColor: Colors.white,
          onPressed: () {
            Clipboard.setData(ClipboardData(text: message));
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('✓ Error copied to clipboard'),
                backgroundColor: Colors.green,
                duration: Duration(seconds: 2),
              ),
            );
          },
        ),
      ),
    );
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Login (Dev)')),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'Dev Login',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
                const SizedBox(height: 20),
                TextFormField(
                  controller: _emailController,
                  decoration: const InputDecoration(
                    labelText: 'Email',
                    border: OutlineInputBorder(),
                  ),
                  validator: (value) =>
                      value == null || value.isEmpty ? 'Enter email' : null,
                  keyboardType: TextInputType.emailAddress,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _passwordController,
                  decoration: const InputDecoration(
                    labelText: 'Password',
                    border: OutlineInputBorder(),
                  ),
                  obscureText: true,
                  validator: (value) =>
                      value == null || value.isEmpty ? 'Enter password' : null,
                ),
                const SizedBox(height: 20),
                _isLoading
                    ? const CircularProgressIndicator()
                    : ElevatedButton(
                        onPressed: _signIn,
                        style: ElevatedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 50),
                        ),
                        child: const Text('Sign In'),
                      ),
                const SizedBox(height: 20),
                TextButton(
                  onPressed: () async {
                    // Example: Sign up a test user if one doesn't exist
                    // In a real app, you'd have a separate sign-up screen
                    try {
                      await Supabase.instance.client.auth.signUp(
                        email: 'test@example.com', // Use a test email
                        password: 'password', // Use a test password
                      );
                      if (!context.mounted) return;
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text(
                            'Test user sign up initiated. Check email for confirmation if enabled, or try logging in if auto-confirm is on.',
                          ),
                        ),
                      );
                    } catch (e) {
                      if (mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            content: Text('Test user sign up error: $e'),
                          ),
                        );
                      }
                    }
                  },
                  child: const Text(
                    '(Dev: Sign Up Test User test@example.com / password)',
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
